ProjetPi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

main/urls.py
from . import views
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('cursus/', views.cursus, name='cursus'),
    path('cv/', views.cv, name='cv'),
    path('cursuscv/', views.cursuscv, name='cursuscv'),
    path('courses/<str:categorie>/', views.courses, name='courses'),
    path('diplomes_details/<int:id>/', views.diplomes_details, name='diplomes_details'),
    path('save_avis/', views.save_avis, name='save_avis'),
    path('save_Payment/', views.save_Payment, name='save_Payment'),
    path('chat/', views.chat, name='chat'),
]

main/models.py
from django.db import models

class Categorie(models.Model):
   
    nom = models.CharField(max_length=100)
    type_diplome = models.CharField(max_length=100)

    def __str__(self):
        return self.nom
class Options(models.Model):
    nom = models.CharField(max_length=100)
   

    def __str__(self):
        return self.nom   

class Diplome(models.Model):
    nom = models.CharField(max_length=100)
    prix = models.IntegerField()
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    option = models.ForeignKey(Options, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.nom

class Avis(models.Model):
    commenter_name = models.CharField(max_length=255)
    diploma_name = models.CharField(max_length=255)
    comment = models.TextField()
    stars = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.commenter_name

class Payment(models.Model):
    cardholder_name=models.CharField(max_length=255)
    card_number=models.IntegerField()
    expiry_date=models.DateField()
    diplome = models.ForeignKey(Diplome, on_delete=models.CASCADE)
    montant=models.IntegerField()
    cvv=models.IntegerField()
    def __str__(self):
        return self.cardholder_name
# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from main.models import Categorie, Diplome,Options,Avis,Payment
from django.dispatch import receiver
from openpyxl import Workbook
import os
def index(request):
    categorie_genie_informatique = Categorie.objects.filter(nom='Diplôme Informatique').first()
    categorie_telecom = Categorie.objects.filter(nom='Diplôme Telecommunication').first()
    categorie_tous = Categorie.objects.filter(nom='Tous Les Diplômes').first()
    categorie_evaluer = Categorie.objects.filter(nom='Evaluer Votre Cv').first()
    somme_diplomes = Diplome.objects.filter(categorie=categorie_genie_informatique).count()
    somme_diplomes_telecom = Diplome.objects.filter(categorie=categorie_telecom).count()
    somme_diplomes_tous = Diplome.objects.all().count()
    aviss = Avis.objects.all()
    context = {
        'categorie_genie_informatique': categorie_genie_informatique,
        'categorie_telecom': categorie_telecom,
        'categorie_tous': categorie_tous,
        'categorie_evaluer': categorie_evaluer,
        'somme_diplomes': somme_diplomes,
        'somme_diplomes_telecom':somme_diplomes_telecom,
        'somme_diplomes_tous':somme_diplomes_tous,
        'aviss':aviss,
    }
    
    return render(request, 'index.html', context)


  
def courses(request, categorie):
    diplomes = Diplome.objects.filter(categorie__nom=categorie)
    option_ids = diplomes.values_list('option_id', flat=True).distinct()
    options = Options.objects.filter(id__in=option_ids)
    return render(request, 'courses.html', {'diplomes': diplomes, 'options': options, 'categorie': categorie})
def diplomes_details(request, id):
    diplome = Diplome.objects.filter(id=id).first()
    return render(request, 'diplome_details.html', {'diplome': diplome})
def save_avis(request):
    if request.method == 'POST':
        commenter_name = request.POST.get('commenter_name')
        diploma_name = request.POST.get('diploma_name')
        comment = request.POST.get('comment')
        stars=request.POST.get('rating')
       

        avis = Avis(commenter_name=commenter_name, diploma_name=diploma_name, comment=comment,stars=stars)
        avis.save()

        return redirect('main:cursuscv')
def save_Payment(request):
    if request.method == 'POST':
        cardholder_name = request.POST.get('cardholderName') 
        card_number = request.POST.get('cardNumber')
        expiry_date = request.POST.get('expiryDate')
        cvv = request.POST.get('cvv')
        montant = request.POST.get('montantDiplome')
       
        diplome=Diplome.objects.filter(id=request.POST.get('nomDiplome')).first()
        payment = Payment(cardholder_name=cardholder_name,card_number=card_number,expiry_date=expiry_date,cvv=cvv,montant=montant,diplome=diplome)
        payment.save()

        return redirect('main:cursus')
def cursus(request):
    return render(request, 'cursus.html')
def cv(request):
    return render(request, 'cv.html')
def chat(request):
    return render(request, 'chat.html')
def cursuscv(request):
    return render(request, 'cursuscv.html')

# Create your views here.

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>RiskReco</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link rel="stylesheet" href="{% static 'assets/img/favicon.ico' %}">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link rel="stylesheet" href="{% static 'assets/lib/animate/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/lib/owlcarousel/assets/owl.carousel.min.css' %}">
  

    <!-- Customized Bootstrap Stylesheet -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">


    <!-- Template Stylesheet -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a href="index.html" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>RiskReco</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a href="{% url 'main:index' %}" class="nav-item nav-link active">Home</a>
                <a href="about.html" class="nav-item nav-link">About</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Courses</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a href="" class="dropdown-item">Tous les cours</a>
                        <a href="{% url 'main:cv' %}" class="dropdown-item">Evaluation de cv </a>
                        <a href="{% url 'main:chat' %}" class="dropdown-item">Chat with RiskReco </a>
                      
                    </div>
                </div>
                <a href="contact.html" class="nav-item nav-link">Contact</a>
            </div>
            <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i class="fa fa-arrow-right ms-3"></i></a>
        </div>
    </nav>
    <!-- Navbar End -->

    {% block content %}
    {% endblock %}
   
        

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Quick Link</h4>
                    <a class="btn btn-link" href="">About Us</a>
                    <a class="btn btn-link" href="">Contact Us</a>
                    <a class="btn btn-link" href="">Privacy Policy</a>
                    <a class="btn btn-link" href="">Terms & Condition</a>
                    <a class="btn btn-link" href="">FAQs & Help</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Contact</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Gallery</h4>
                    <div class="row g-2 pt-2">
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="{% static 'assets/img/course-1.jpg' %}" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="{% static 'assets/img/course-2.jpg' %}" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="{% static 'assets/img/course-3.jpg' %}" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="{% static 'assets/img/course-2.jpg' %}" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="{% static 'assets/img/course-3.jpg' %}" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="{% static 'assets/img/course-1.jpg' %}" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Newsletter</h4>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a><br><br>
                        Distributed By <a class="border-bottom" href="https://themewagon.com">ThemeWagon</a>
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'assets/lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'assets/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'assets/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/lib/waypoints/waypoints.min.js' %}"></script>
    
   

    <!-- Template Javascript -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>

main/templates/chat.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}

<div class="container-fluid bg-primary py-5 mb-5 page-header">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-10 text-center">
                <h1 class="display-3 text-white animated slideInDown">RiskReco</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center">
                        <li class="breadcrumb-item"><a class="text-white" href="#">The #1 recommendation service in Risk Management</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">Contact</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- Header End -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Chat</h6>
            <h1 class="mb-5">RiskReco Chat</h1>
        </div>         
          
    <form method="post" id="chat-form" class="form-horizontal">
        {% csrf_token %}
        
        <label for="message">What do you want to learn about ? </label>

        <div class="d-flex mb-6" style="margin:10px;">
            <div class="form-outline me-3" style="width: 25rem">
        <input type="text" class="form-control" name="message" id="message" autocomplete="off" placeholder="Ex: Risk Management">
            </div>
    
        <button class="btn btn-primary btn-sm " type="submit">Send</button>

        </div>

    </form>
    <div id="chat-log" class="wrapper"></div>
</div>
</div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#chat-form').submit(function(event) {
                event.preventDefault();
                $.ajax({
                    url: '/chat/',
                    method: 'POST',
                    data: $(this).serialize(),
                    success: function(data) {
                        $('#chat-log').append('<div class="msg-container left"><p class="msg "><strong>You :</strong>' + $('#message').val() + '</p></div>');
                        $('#chat-log').append('<div class="msg-container right"><p class="msg "><strong>RiskReco :</strong>' + data.bot_response + '</p></div><br>');
                        $('#message').val('');
                        
                    }
                });
            });
        });
    </script>

{% endblock %}

main/templates/courses.html
   {% extends 'base.html' %}
   {% load static %}
   {% block title %}Home{% endblock %}
   
   {% block content %}

    <div class="container-fluid bg-primary py-5 mb-5 page-header">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Data Science</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="#">Home</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="#">Pages</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Courses</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
   
    {% for option in options %}
        <div class="container-xxl py-5">
            <div class="container">
              
                    <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                        <h6 class="section-title bg-white text-center text-primary px-3">diplome</h6>
                        <h1 class="mb-5">{{ option.nom }}</h1>
                    </div>
                    <div class="row g-4 justify-content-center">
                        {% for diplome in diplomes %}
                            {% if diplome.option == option %}
                        <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                                    <!-- Course block for each option -->
                                    <div class="course-item bg-light">
                                        <!-- Course content -->
                                        <div class="position-relative overflow-hidden">
                                            <!-- Course image -->
                                            <img class="img-fluid" src="{% static 'assets/img/course-1.jpg' %}" alt="">
                                            <!-- Course buttons -->
                                            <div class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                                                <a href="{% url 'main:diplomes_details' id=diplome.id %}" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">Read More</a>
                                                <a id="openPopupBtn-{{ diplome.id }}"class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Join Now</a>
                                            </div>
                                        </div>
                                        <!-- Course details -->
                                        <div class="text-center p-4 pb-0">
                                            <h3 class="mb-0">{{ diplome.prix }} TND</h3>
                                            <div class="mb-3">
                                                <small class="fa fa-star text-primary"></small>
                                                <small class="fa fa-star text-primary"></small>
                                                <small class="fa fa-star text-primary"></small>
                                                <small class="fa fa-star text-primary"></small>
                                                <small class="fa fa-star text-primary"></small>
                                                <small>(123)</small>
                                            </div>
                                            <h5 class="mb-4">{{ diplome.nom }}</h5>
                                        </div>
                                        <!-- Course stats -->
                                        <div class="d-flex border-top">
                                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-user-tie text-primary me-2"></i>John Doe</small>
                                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>1.49 Hrs</small>
                                            <small class="flex-fill text-center py-2"><i class="fa fa-user text-primary me-2"></i>30 Students</small>
                                        </div>   
                                    </div>
                        </div>
                        <div id="overlay" class="overlay">
                            <div id="paymentPopup" class="popup">
                                <div class="popup-content">
                                    <span class="close">&times;</span>
                                  
                                    
                                    <form id="paymentForm" method="POST" action="{% url 'main:save_Payment' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="montantDiplome" value="{{ diplome.prix }}">
                                        <input type="hidden" name="nomDiplome" value="{{ diplome.id }}">
                                        <h3 id="montantDiplome" name="montantDiplome"></h3>
                                        <div class="row g-3">
                                            <div class="col-md-6">
                                                <div class="form-floating">
                                                    <!-- Icône utilisateur -->
                                                    <input type="text" class="form-control" id="cardholderName" name="cardholderName" placeholder="Votre nom">
                                                    <label for="cardholderName"> <i class="fas fa-user input-icon"></i>Nom du titulaire de la carte(Nom de l'universite)</label>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-floating">
                                                     <!-- Icône carte de crédit -->
                                                     <input type="text" class="form-control" id="cardNumber" name="cardNumber" placeholder="Numéro de carte" maxlength="16" oninput="formatCardNumber(this)" required>
                                                     <label for="cardNumber"><i class="fas fa-credit-card input-icon"></i>Numéro de carte</label>
                                                </div>    
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-floating">
                                                     <!-- Icône calendrier -->
                                                    <input type="date" class="form-control" id="expiryDate" name="expiryDate"   placeholder="Date d'expiration">
                                                    <label for="expiryDate"><i class="fas fa-calendar-alt input-icon"></i>Date d'expiration</label>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-floating">
                                                    <!-- Icône cadenas -->
                                                    <input type="password" class="form-control" id="cvv" name="cvv"  placeholder="CVV">
                                                    <label for="cvv"><i class="fas fa-lock input-icon"></i> CVV</label>
                                                </div>
                                            </div>
                                           
                                            <div class="col-12">
                                                <button class="btn btn-primary w-100 py-3 pay-btn"  type="submit">Payer</button>
                                            </div>
                                        </div>
                                    </form>
                                    
                                    
                                </div>
                            </div>
                        </div>
                        
                        {% endif %}
                        {% endfor %}
                    </div>
                    
                    
                </div>
               
            </div>
        </div>
        {% endfor %}
        
   

   


<!-- Superposition modale -->


<style>
    .overlay {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        z-index: 9999;
    }
    
    .popup {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        z-index: 99999;
    }
    
    .popup-content {
        position: relative;
    }
    
    .close {
        position: absolute;
        top: 10px;
        right: 10px;
        font-size: 20px;
        cursor: pointer;
    }
    
    .close:hover {
        color: #f00;
    }
    
    .pay-btn {
        background-color: #4CAF50;
        color: #fff;
    }
    
</style>

<script>
  
    // Fonction pour ouvrir la superposition modale
    function openModal() {
        document.getElementById("overlay").style.display = "block";
    }

    // Fonction pour fermer la superposition modale
    function closeModal() {
        document.getElementById("overlay").style.display = "none";
    }
   
      

    // Écouteur d'événement pour le bouton d'ouverture de la superposition modale
    {% for diplome in diplomes %}
    document.getElementById("openPopupBtn-{{ diplome.id }}").addEventListener("click", function() {
        openModal();
        // Additional code specific to each option can be placed here
    });
    
 
    {% endfor %}

    // Écouteur d'événement pour le bouton de fermeture de la superposition modale
    document.getElementsByClassName("close")[0].addEventListener("click", closeModal);

    // Écouteur d'événement pour le bouton "Payer"
    document.querySelector("#paymentPopup .pay-btn").addEventListener("click", function() {
        window.location.href = "{% url 'main:cursus' %}"; 
        window.close();// Remplacez 'main:cursus' par le nom de l'URL approprié dans votre projet Django
    });
</script>

    <!-- Courses End -->


    <!-- Testimonial Start -->
    
    <!-- Testimonial End -->
        
    {% endblock %}